config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :messages

  resources :users do
    get :blogs, on: :member
    post :add_friend, on: :collection
    get :friends, on: :member
  end
  resources :sessions
  resources :blogs do
    resources :blog_contents
  end

  

  namespace :admin do
    root 'users#index'

    resources :users do 
      collection do
        get :search
      end
     end   
   end


end

app/models/blog.rb
class Blog < ActiveRecord::Base
  validates :title, presence: { message: "标题不能为空" }
  validates :content, presence: { message: "内容不能为空" }
  validates :user_id, presence: { message: "用户不能为空" }

  belongs_to :user
  has_many :blogs_tags, class_name: "BlogsTags"
  has_many :tags, through: :blogs_tags
  has_many :blog_contents, class_name: "BlogContent"
  
  def tags_string= one_tags
    self.tags.destroy_all
    one_tags.split(',').each do |tag|
      one_tag = Tag.find_by(title: tag)
      one_tag = Tag.new(title: tag) unless one_tag
      self.tags << one_tag
    end
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  before_filter :auth_user, except: [:index, :show]


  def index
    @blogs = Blog
      .page(params[:page] || 1)
      .per_page(params[:per_page] || 7)
      .order("id desc")
      .where(is_public: true)
      .includes(:tags, :user)
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = current_user.blogs.new(blog_attrs)
    if @blog.save

      flash[:notice] = "博客创建成功"
      redirect_to blogs_path
    else

      flash[:notice] = "博客创建失败"
      render action: :new
    end
  end

  def show
    @blog_content = BlogContent.new
    @blog = Blog.find params[:id]
    if logged_in?
      user_id = current_user.id
      blog_id = @blog.id
      @user_record = UserRecord.new(user_id: user_id, blog_id: blog_id)
      @user_record.save
    end
  end

  def edit
    @blog = current_user.blogs.find params[:id]
    render action: :new
  end

  def update
    @blog = current_user.blogs.find params[:id]
    @blog.attributes = blog_attrs
    if @blog.save

      flash[:notice] = "博客更新成功"
      redirect_to blogs_path
    else
      
      flash[:notice] = "博客更新失败"
      render action: :new
    end
  end


  private

  def blog_attrs
    params.require(:blog).permit(:title, :content, :is_public, :tags_string)
  end



end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_blogs.html.erb
<table class="table">
      <tr>
        <th>ID</th>
        <th>标题</th>
        <th>作者</th>
      </tr>
      <% @blogs.each do |blog| %>
        <tr>
          <td><%= blog.id %></td>
          <td>
            <%= link_to blog.title, blog_path(blog) %>
            <% blog.tags.each do |tag| %>
              <span class="badge"><%= tag.title %></span>
            <% end -%>
          </td>
          <td><%= blog.user.username %></td>
            <td>
        <% if blog.user == current_user %>
          <%= blog.is_public ? "显示" : "不显示" %>

          <%= link_to "编辑", edit_blog_path(blog) %>
        <% end -%>
      </td>
        </tr>
      <% end -%>
    </table>


    <div class="col-sm-4">
    </div>
    <div class="col-sm-4">
      <%= will_paginate @blogs%>
    </div>
    <div class="col-sm-4">
    </div>

app/views/blogs/index.html.erb
<h1>博客</h1>

<div>
  <%= link_to "创建博客", new_blog_path, class: "btn btn-primary" %>
  <% if logged_in? %>
    <%= link_to "我的博客", blogs_user_path(current_user), class: "btn btn-default" %>
  <% end -%>
</div>

<div class="row">
  <div class="col-sm-12">
  <%= render "blogs" %>
  </div>
</div>

app/views/blogs/new.html.erb
<h1><%= @blog.new_record? ? '创建' : '编辑' %>博客</h1>

<div class="row">
  <div class="col-sm-5">
    <%= form_for @blog, url: (@blog.new_record? ? blogs_path : blog_path(@blog)), method: (@blog.new_record? ? :post : :put) do |f| %>
      <div class="form-group">
        <ul class="list-unstyled">
          <% @blog.errors.messages.values.flatten.each do |error| %>
            <li><i class="fa fa-exclamation-circle"></i> <%= error %></li>
          <% end -%>
        </ul>
      </div>
      <% if @blog.new_record?%>
        <div class="form-group">
          <%= f.hidden_field :content_counts, value: '0' %>
        </div>
      <% end -%>
      <div class="form-group">
        <%= f.text_field :title, class: "form-control", placeholder: "标题" %>
      </div>

      <div class="form-group">
        <%= f.text_area :content, class: "form-control", placeholder: "内容" %>
      </div>

      <div class="form-group">
        <input type="text" name="blog[tags_string]" value="<%= @blog.tags.map(&:title).join(',') %>" /><small>标签以逗号分隔</small>
      </div>

      <div class="form-group">
        <% [[true, "显示"], [false, "不显示"]].each do |public| %>
          <input type="radio" name="blog[is_public]" value="<%= public.first %>" <%= 'checked' if @blog.is_public == public.first %> /> <%= public.last %>
        <% end -%>
      </div>

      <%= f.submit "保存", class: "btn btn-primary" %> 
    <% end -%>
  </div>

  <div class="col-sm-7">
  </div>
</div>

app/views/blogs/show.html.erb
<div class="row">
	<div class="col-sm-2"></div>
  <div class="col-sm-8">

  	<h1><%= @blog.title %></h1>
  	<p>----------------------------------------</p>
    <p>作者: <%= @blog.user.username %>, <%= @blog.created_at %></p>
    <p>----------------------------------------</p>
   
    <%= @blog.content %>
    <p>----------------------------------------</p>

    <p>回复</p>

    <p><%= @blog.content_counts %></p>
    <p>----------------------------------------</p>
    <table class="table">
      <tr>
        <th>ID</th>
        <th>回复内容</th>
        <th>回复人</th>
        <th>回复时间</th>
        <th></th>
      </tr>
    	<% @blog.blog_contents.each do |content| %>
     	<tr>
     		<td><%= content.id %></td>
     		<td><%= content.content %></td>
     		<td><%= content.user.username %></td>
     		<td><%= content.created_at%></td>
     		<td>
     		<% if content.user == current_user %>
     			<%= link_to "删除", blog_blog_content_path(@blog, content.id), method: :delete, class: "btn btn-primary" %>
     		<% end -%>
     		</td>
     	</tr>
    	<% end -%>
    </table>
   	<%= form_for @blog_content, url: blog_blog_contents_path(@blog), method: :post do |f| %>
   	
     	<div class="form-group">
       	<%= f.hidden_field :blog_id, value: @blog.id %>
      </div>
      <div class="form-group">
       	<%= f.text_area :content, class: "form-control", placeholder: "内容" %>
      </div>
      <div class="form-group">
      <%= f.submit "回复", class: "btn btn-primary" %> 
      </div>
    <% end -%> 

  </div>

  <div class="col-sm-2">
  </div>
</div>