config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :messages

  resources :users do
    get :blogs, on: :member
    post :add_friend, on: :collection
    get :friends, on: :member
  end
  resources :sessions
  resources :blogs do
    resources :blog_contents
  end

  

  namespace :admin do
    root 'users#index'

    resources :users do 
      collection do
        get :search
      end
     end   
   end


end

app/models/user.rb
class User < ActiveRecord::Base

  validates :username, presence: { message: "用户名不能为空" }
  validates :username, uniqueness: { message: "用户名已存在" }

  has_many :blogs
  has_many :blog_contents, class_name: :BlogContent
  has_many :friendships
  has_many :friends, through: :friendships, source: :friend
  has_many :inboxes, class_name: :Message, foreign_key: :receiver_id
  has_many :outboxes, class_name: :Message, foreign_key: :receiver_id
  has_many :user_records, class_name: "UserRecord"
  has_many :public_blogs, -> { where(is_public: true) },
    class_name: "Blog"

  has_one :latest_blog,  -> { order("id desc") }, class_name: :Blog

  before_save :update_username

  attr_accessor :oldpassword
  attr_accessor :password
  attr_accessor :password_confirmation

  validate :validate_password, on: :create
  validate :change_password, on: :update
  
  before_create :set_password
  before_save :set_password

  def self.authenticate username, password
    user = find_by(username: username)
    if user and user.valid_password?(password)
      user
    else
      nil
    end
  end
  
  def add_friend user
    if self == user
      false
    else
      self.friends << user
      user.friends << self
    end

  end

  def is_friend_with? user
    self.friendships.exists?(friend_id: user.id)
    
  end

  def valid_password? password
    self.crypted_password == Digest::SHA256.hexdigest(password + self.salt)
  end


  private

  def change_password
    if valid_password? self.oldpassword
      password_isblank?
      password_notsame?
    end
    return true
  end

  def validate_password
    password_isblank?
    password_notsame?
    return true
  end

  def password_isblank?
    if self.password.blank?
      self.errors.add(:password, "密码不能为空")
      return false
    end
  end

  def password_notsame?
    unless self.password == self.password_confirmation
      self.errors.add(:password_confirmation, "密码不一致")
      return false
    end
  end

  def set_password
    self.salt = Time.now.to_i
    self.crypted_password = Digest::SHA256.hexdigest(self.password + self.salt)
  end


  def update_username
    self.username = self.username.downcase
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  layout 'admin'
  def index
    @users = User.page(params[:page] || 1).per_page(params[:per_page] || 10).order("id desc")
  end

  def search
    @users = User.page(params[:page] || 1).per_page(params[:per_page] || 10)
      .order("id desc").where(["username like ?", "%#{params[:username]}%"])

    render action: :index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :auth_user, only: [:index]

  def index
    @users = User.page(params[:page] || 1).per_page(params[:per_page] || 10)
      .order("id desc")
  end

  def blogs
    @blogs = current_user.blogs.page(params[:page] || 1).per_page(params[:per_page] || 8)
      .order("id desc")
  end
  
  def new
    @user = User.new
  end

  def add_friend
    if current_user.add_friend(User.find(params[:friend_id]))
      flash[:notice] = "添加成功"
      redirect_to :back
    else
      flash[:notice] = "添加失败"
      redirect_to :back
    end  
  end

  def friends
    @friends = current_user.friends.page(params[:page] || 1).per_page(params[:per_page] || 8)
      .order("id desc")
  end

  def create
    @user = User.new(user_attrs)
    if @user.save
      flash[:notice] = "注册成功，请登录"
      redirect_to new_session_path
    else
      render action: :new
    end
  end

  def edit
    @user = User.find params[:id]
    render action: :new
  end

  def update
    current_user.attributes = password_attrs
    if current_user.save
      flash[:notice] = "密码修改成功，请登录"
      logout_user
      redirect_to new_session_path
    else
      flash[:notice] = "密码修改失败，请重新修改"
      render action: :new
    end
  end



  private
  def user_attrs
    params.require(:user).permit(:username, :password, :password_confirmation)
  end

  def password_attrs
    params.require(:user).permit(:oldpassword, :password, :password_confirmation)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/blogs.html.erb
<h1><%= current_user.username %>的博客</h1>

<div>
  <%= link_to "创建博客", new_blog_path, class: "btn btn-primary" %> 
  <%= link_to "我的博客", blogs_user_path(current_user), class: "btn btn-default" %>
</div>

<div class="row">
  <div class="col-sm-12">
  <%= render "blogs/blogs" %>
  </div>
</div>

app/views/users/friends.html.erb
<div class="row">
  <div class="col-sm-2"></div>
  <div class="col-sm-8">
    <%= link_to "用户列表", users_path, class: "btn btn-primary" %>
    <%= link_to "我的好友", friends_user_path(current_user), class: "btn btn-primary" %>
    <table class="table">
      <tr>
        <th>ID</th>
        <th>用户名</th>
        <th></th>
      </tr>
      <% @friends.each do |friend| %>
        <tr>
          <td><%= friend.id %></td>
          <td><%= friend.username %></td>
          <td>
            delete
          </td>
        </tr>
      <% end -%>
    </table>

    <%= will_paginate @friends %>
  </div>
  <div class="col-sm-2"></div>
</div>

app/views/users/index.html.erb
  

<div class="row">
  <div class="col-sm-2"></div>
  <div class="col-sm-8">
    <a href="#" class="btn btn-primary">用户列表</a>
    <%= link_to "我的好友", friends_user_path(current_user), class: "btn btn-primary" %>
    <table class="table">
      <tr>
        <th>ID</th>
        <th>用户名</th>
        <th>操作</th>
      </tr>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.id %></td>
          <td><%= user.username %></td>
          <% if  current_user.is_friend_with? user %>
            <td></td>
          <% else %>
          <td><%= link_to "add_friend", add_friend_users_path(friend_id: user.id), method: :post, class: "btn btn-default" %></td>
          <% end -%>
        </tr>
      <% end -%>
    </table>

    <%= will_paginate @users %>
  </div>
  <div class="col-sm-2"></div>
</div>

app/views/users/new.html.erb
<h1><%= @user.new_record? ? '注册' : '编辑' %>用户</h1>
<div class="row">
  <div class="col-sm-5">
    <%= form_for @user, url: (@user.new_record? ? users_path : user_path(@user)), method: (@user.new_record? ? :post : :put) do |f| %>
      <div class="form-group">
        <ul class="list-unstyled">
          <% @user.errors.messages.values.flatten.each do |error| %>
            <li><i class="fa fa-exclamation-circle"></i> <%= error %></li>
          <% end -%>
        </ul>
      </div>
      <% if @user.new_record? %>
      <div class="form-group">
        <%= f.text_field :username, class: "form-control", placeholder: "用户名" %>
      </div>
      <% else %>
      <div class="form-group">
        <%= f.text_field :oldpassword, class: "form-control", placeholder: "原密码" %>
      </div>
      <% end -%>
      <div class="form-group">
        <%= f.password_field :password, class: "form-control", placeholder: "密码" %>
      </div>
      <div class="form-group">
        <%= f.password_field :password_confirmation, class: "form-control", placeholder: "密码确认" %>
      </div>
      <% if @user.new_record? %>
      <%= f.submit "注册", class: "btn btn-primary" %> 
      <%= link_to "登录", new_session_path %>
      <% else %>
       <%= f.submit "保存", class: "btn btn-primary" %>
      <% end -%>
    <% end -%>
  </div>

  <div class="col-sm-7">
  </div>
</div>